before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
python:
    - 2.7
script:
    - python -m unittest discover -v
