env:
    global:
        secure: PNI5qMHhEdHbUSAIIGL2u/27bb7CHgy0Ql84XOL9pt++0CMB5rh0Q01GTHkALYaMZ9Nzq7eqm8jqC0lDaQVUlm+vJIfyJCJ1nIcMs3dCp/7vH14u/xj+bEpNEhQJUScDfLuhQE1fKF5yjUhBopVzh9EBGvpwaOGrkF7zy6ohjMY=
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
    - echo $pypirc_password | gpg --passphrase-fd 0 .travis/pypirc.gpg
    - mv .travis/pypirc ~/.pypirc
install:
    - sudo apt-get install -qq gcc g++ build-essential
    - sudo apt-get install -qq sqlite
    - sudo apt-get install -qq libkyotocabinet-dev
    - sudo pip install virtualenv
    - virtualenv venv
    - venv/bin/pip install -r requirements.txt
    - venv/bin/pip install coveralls
python:
    - 2.7
script:
    - venv/bin/coverage run -m unittest discover -v
after_success:
    - venv/bin/coveralls
    - git describe --long --tags | sed 's/-\([^-]\+\)-.*/.dev\1/g' > version
    - python setup.py sdist upload
