services:
    - cassandra
language:
    python
before_install:
    - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu/ trusty main universe"
    - sudo apt-get update -qq
install:
    - sudo apt-get install -qq gcc g++ build-essential
    - sudo apt-get install -qq sqlite
    - sudo apt-get install -qq libkyotocabinet-dev
    - pip install -r requirements.txt
    - pip install coveralls
python:
    - 2.7
    - 3.4
script:
    - coverage run -m unittest discover -v
after_success:
    - coveralls
deploy:
    provider: pypi
    user: chm.duquesne
    password:
        secure: BwkOtw3rQxJ4r8DUNJSndmO/08zRk9ZTcNw+7Mw5CyiqHl9RjTTUrUSgFzxDDtSkBdIzlsUCPFVuqL5SIC1adw8Uof9BNRYZPccL8knrtQe7dqF0rkE6O2PVvF1SCyurKqCmRKy9LZBzxIok+YX67tuWmjbngOmf/JLyuN/rIF0=
